apiVersion: v1
kind: Namespace
metadata:
  name: red-blue-ingress
---
kind: Pod
apiVersion: v1
metadata:
  name: red-app
  namespace: red-blue-ingress
  labels:
    app: red
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --http=true
    - --port=8080
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: red-app
---
kind: Service
apiVersion: v1
metadata:
  name: red-service
  namespace: red-blue-ingress
spec:
  selector:
    app: red
  ports:
  # Default port used by the image
  - port: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: blue-app
  namespace: red-blue-ingress
  labels:
    app: blue
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --http=true
    - --port=8080
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: blue-app
---
kind: Service
apiVersion: v1
metadata:
  name: blue-service
  namespace: red-blue-ingress
spec:
  selector:
    app: blue
  ports:
  # Default port used by the image
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-selector-ingress
  namespace: red-blue-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /red
        backend:
          service:
            name: red-service
            port:
              number: 8080
      - pathType: Prefix
        path: /blue
        backend:
          service:
            name: blue-service
            port:
              number: 8080
---