{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: dockerprivatesecret
  labels:
    {{- include "helloapp.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
