apiVersion: v1
kind: Namespace
metadata:
  name: red-blue-lb
---
kind: Pod
apiVersion: v1
metadata:
  name: red-app
  namespace: red-blue-lb
  labels:
    app: http-echo
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --http=true
    - --port=8080
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: red-app
---
kind: Pod
apiVersion: v1
metadata:
  name: blue-app
  namespace: red-blue-lb
  labels:
    app: http-echo
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --http=true
    - --port=8080
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: blue-app
---
kind: Service
apiVersion: v1
metadata:
  name: red-blue-service
  namespace: red-blue-lb
spec:
  type: LoadBalancer
  selector:
    app: http-echo
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: red-blue-ingress
  namespace: red-blue-lb
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: red-blue-service
            port:
              number: 8080
---