apiVersion: v1
kind: Namespace
metadata:
  name: configmap-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: configmap-content
data:
  index.html: |
    <html>
    <h1>HTML Images</h1>
    <body>
    <p>HTML images are defined with the img tag:</p>
    <p>targeting external source</p>
    <img src="https://kind.sigs.k8s.io/logo/logo.png" alt="https://kind.sigs.k8s.io" width="200" height="200">
    </body>
    </html>
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-app
  namespace: configmap-content
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-index-file
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file
        configMap:
          name: index-html-configmap
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-configmap-service
  namespace: configmap-content
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-configmap-ingress
  namespace: configmap-content
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-configmap-service
            port:
              number: 80
---