kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # bind specific ip addresses to allow reach it from other containeres.
  apiServerAddress: "$MY_PRIVATE_IP"
  apiServerPort: 6443
  # enable dualstack
  ipFamily: dual
  # Both IPv4 and IPv6 subnets must be specified in dual-stack mode
  podSubnet: "10.244.0.0/16,fd00:10:244::/56" # IPv4 first, then IPv6 for Calico compatibility
  serviceSubnet: "10.96.0.0/12,fd00:10:96::/112" # IPv4 first, then IPv6
  # ipvs mode
  kubeProxyMode: ipvs
# Add local registry
containerdConfigPatches:
# patches for local registry
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
# patches for prometheus
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  # patches for enable admission puglins
  apiServer:
    extraArgs:
      "enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction"
  # configure controller-manager bind address
  controllerManager:
    extraArgs:
      bind-address: "::"
  # configure etcd metrics listen address
  etcd:
    local:
      extraArgs:
        listen-metrics-urls: "http://[::]:2381"
  # configure scheduler bind address
  scheduler:
    extraArgs:
      bind-address: "::"
- |-
  kind: KubeProxyConfiguration
  # configure proxy metrics bind address
  metricsBindAddress: "::"
# nodes configuration and ingress port mapping
nodes:
- role: control-plane
  extraPortMappings:
  # IPv4
  - containerPort: 31437
    hostPort: 80
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 31438
    hostPort: 443
    protocol: TCP
    listenAddress: "0.0.0.0"
  # IPv6
  - containerPort: 31437
    hostPort: 8080
    protocol: TCP
    listenAddress: "::"
  - containerPort: 31438
    hostPort: 8443
    protocol: TCP
    listenAddress: "::"
  # Remove default control-plane taint so gateway pods can schedule here
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    skipPhases:
      - mark-control-plane
- role: worker
- role: worker
