apiVersion: v1
kind: Namespace
metadata:
  name: statelessnginx
---
apiVersion: v1
kind: Pod
metadata:
  name: stateless-nginx
  namespace: statelessnginx
spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

