apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-deploy-scaler
  namespace: initcontainer
spec: 
  scaleTargetRef:
    name: nginx-deploy
  pollingInterval: 10
  cooldownPeriod: 0
  minReplicaCount: 3
  triggers :
  - type: cron
    metadata: 
      timezone: Europe/Lisbon
      start: 36 * * * *
      end: 40 * * * *
      desiredReplicas: "10"