prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
  route:
    main:
      enabled: true
      hostnames: 
      - "prometheus.$MY_PRIVATE_IP.nip.io"
      parentRefs:
      - name: nginx-shared-gateway
        namespace: nginx-gateway
      httpsRedirect: false
      matches:
        - path:
            type: PathPrefix
            value: /
alertmanager:
  route:
    main:
      enabled: true
      hostnames: 
      - "alertmanager.$MY_PRIVATE_IP.nip.io"
      parentRefs:
      - name: nginx-shared-gateway
        namespace: nginx-gateway
      httpsRedirect: false
      matches:
        - path:
            type: PathPrefix
            value: /

grafana:
  route:
    main:
      enabled: true
      hostnames: 
      - "grafana.$MY_PRIVATE_IP.nip.io"
      parentRefs:
      - name: nginx-shared-gateway
        namespace: nginx-gateway
      httpsRedirect: false
      matches:
        - path:
            type: PathPrefix
            value: /
  grafana.ini:
    server:
      domain: grafana.monitoring
      root_url: "http://grafana.monitoring:80/"
      enforce_domain: false
  additionalDataSources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki.monitoring:3100
    access: proxy
    isDefault: false
    jsonData:
      derivedFields:
      - datasourceUid: tempo
        matcherRegex: "traceID=(\\w+)"
        name: TraceID
        url: "$${__value.raw}"
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo.monitoring:3200
    access: proxy
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
        tags:
        - key: "service.name"
          value: "app"
        customQuery: true
        query: '{$${__tags}} |= "$${__trace.traceId}"'
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
kubeEtcd:
  service:
    targetPort: 2381