apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nginx-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/ngix_deploy
    targetRevision: HEAD
    path: development
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx-deploy
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
