include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

terraform {
  source = "../../../../modules/gitea-runner"
}

# This unit only needs the kubernetes provider (generated by root.hcl). No vault
# provider here — the registration token is minted at runtime by
# register-gitea-runner.sh (admin creds sourced from OpenBao), not by Terraform.

# Reusable unit — per-deployment config comes from the stack via `values`.
inputs = {
  namespace          = values.namespace
  gitea_internal_url = values.gitea_internal_url
  token_secret_name  = try(values.token_secret_name, "gitea-runner-token")

  runner_capacity   = try(values.runner_capacity, 1)
  default_job_image = try(values.default_job_image, "node:20-bookworm")
}
