name: Publish to Docker
on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mkilikrates/sam-cdk-tf
          # tags: type=sha
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          file: sam-cdk-tf-pythonSlimDinD.dockerfile
          context: "{{defaultContext}}:Docker/tools/Docker"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  cleanup:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Login to GitHub Container Registry with PAT_TOKEN
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ghcr.io
          untagged_only: true
          owner_type: user